### ISSUE TITLE
Configuring for Heroku

### ISSUE THREAD

**Issue by southpolesteve** [southpolesteve/deploy_button#2]
Currently, there is no way to configure the app for deployment. Running migrations, setting config vars, provisioning add-ons, etc. I am thinking of documenting a Travis-CI style yaml file that sits in the base of the repo and specs these tasks. What this might look like:

``` yaml
addons:
 - redis:basic
before_deploy:
- cp Gemfile.heroku Gemfile
after_deploy:
 - rake db:migrate
config:
 PAYEE_NAME:
  help: This is the name of the person who will be payed
  label: Payee Name
  required: true
  default: John Doe
```
